# description of this workflow, can be anything you want
name: PushReadme

# we need to let GitHub know _when_ we want to release, typically only when we create a new tag.
# this will target only tags, and not all pushes to the master branch.
# this part can be heavily customized to your liking, like targeting only tags that match a certain word,
# other branches or even pullrequests.
on:
  workflow_dispatch:
  push:
    paths:
    - 'README.md' 
   

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "request" is a job, you can name it anything you want
  pushData:
    runs-on: ubuntu-latest
    steps:  
      - name: Clone project
        uses: actions/checkout@v3
      - name: Pushes readme to Website repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}} 
        with:
          source_file: 'README.md'
          destination_repo: 'Jodsderechte/Jodsderechte.github.io'
          destination_folder: 'Addons/AutoDoors/'
          user_email: ${{ secrets.USER_MAIL }}
          user_name: ${{ secrets.USER_NAME }}
          commit_message: 'Update DungeonAuraTools for newest ReadMe version'
